# This file contains values from Cookiecutter

default_context:
  project_name: "kindledb-common"
  project_description: "Awesome `kindledb-common` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "TakashiAihara"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.10
  github_name: "TakashiAihara"
  email: "takashi.aihara.0523@gmail.com"
  version: "0.1.1"
  line_length: "88"
  create_example_template: "none"
